### ISSUE TITLE
Detected by Windows Defender

### ISSUE THREAD

**Issue by merlin123h** [quantumcored/paradoxiaRAT#12]
Hi.
the payload is detected by windows Defender.
please FUD the file.
thanks

**Comment by augustgl** [comment]
You have to make the file FUD yourself with a crypter, a packer, or obfuscation. It is not his responsibility to FUD files for you. Once the antivirus engines have the paradoxias signature, it’s the users job to make files FUD. We aren’t your personal army.

**Comment by quantumcore** [comment]
![meme](https://i.imgflip.com/4poagz.jpg)
