### ISSUE TITLE
20 seconds have passed and we have received no response from Paradoxia

### ISSUE THREAD

**Issue by phanthuthao** [quantumcored/paradoxiaRAT#13]
paradoxia >> (192.168.0.102:49835) : chromedump
[i] 20 seconds have passed and we have received no response from Paradoxia. There may be a problem.
[i] 20 seconds have passed and we have received no response from Paradoxia. There may be a problem.

**Comment by quantumcore** [comment]
There might be a problem if the client hasn't responded for more than 20 seconds, Try waiting more or restarting paradoxia server.

**Comment by phanthuthao** [comment]
Thanks a lot!
