### ISSUE TITLE
Can't build the Client.exe on ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by pssolanki111** [quantumcored/paradoxiaRAT#15]
Hi there Fahad,

Thanks for the excellent tool :)

I'm having issues building the client on my ubuntu 20.04 LTS.  I have all the python dependencies installed and verified. The Paradoxia console comes up. 
below is what it says when I try to build it

```
paradoxia >> build
[+] Host : 127.0.0.1
[+] Port : 443
[+] Installation Name (.exe) : ParadoxiaClient.exe
[+] Installation Folder name : Paradoxia
[+] Output file name (.exe) : file.exe
[?] Would you like to build with Icon? (Y/n) : n
[X] Error building Paradoxia Client.
paradoxia >> 
```

It just says `error building client`. No helpful debug info. Is there any log file which keeps track of actual errors or what could be the reason of the build failing?

Thanks for any suggestions :)

**Comment by quantumcore** [comment]
Hey there Solanki!  :)
Sorry I'm late, I didn't see this before.

To see the Error that occurs when building, you need to edit the source.
https://github.com/quantumcored/paradoxiaRAT/blob/master/kernel/builder.py#L32
Remove ``stdout = subprocess.DEVNULL`` from Line 44 and 49, Save & close and retry building.

The error should be visible then.

**Comment by pssolanki111** [comment]
Thanks for the response, Fahad! 
I'm editing the source to redirect the `stdout` pipeline to `stdout` itself :D 
I'll let ya know how that went : )

**Comment by quantumcore** [comment]
Alright, looking forward to your reply.

**Comment by pssolanki111** [comment]
Hi there @quantumcore,
here is what I get after redirecting `stdout` back to `stdout` from `sp.DEVNULL`.

```
paradoxia >> build
[+] Host : 127.0.0.1
[+] Port : 443
[+] Installation Name (.exe) : ParadoxiaClient.exe
[+] Installation Folder name : Paradoxia
[+] Output file name (.exe) : file.exe
[?] Would you like to build with Icon? (Y/n) : n
i686-w64-mingw32-gcc main.c paradoxia.c ParadoxiaClient.c sys.c LoadLibraryR.c GetProcAddressR.c  -o file.exe -lws2_32 -static -liphlpapi -m32 -mwindows  -lwinmm -lpsapi -lwininet -lshlwapi -MD -s -O3
make: i686-w64-mingw32-gcc: Command not found
make: *** [makefile:19: main] Error 127
[X] Error building Paradoxia Client.
paradoxia >>


``` I'm pretty sure I have build tools installed. (`build-essentials`). what else do I need? any distro of gcc compiler maybe?
Note sure. Please let me know :)

Thanks again

**Comment by quantumcore** [comment]
'apt-get install mingw-w64'

You're missing mingw cross compiler. It should work now. :)

**Comment by pssolanki111** [comment]
I'll try that :) thanks for the prompt reply. 

And thanks for the great work on the tool :)

**Comment by pssolanki111** [comment]
...and it works :)

Thanks & Regards...
