### ISSUE TITLE
MOVE FROM MAIN() TO WINMAIN()

### ISSUE THREAD

**Issue by s1st3r** [quantumcored/paradoxiaRAT#6]
Your entry point needs to be changes.

Also use #define _CRT_SECURE_NO_WARNINGS

Which Visual Studio version did you use for compiling?

**Comment by s1st3r** [comment]
Thank you.

i have never coded WINAPI C/C++ on Linux platform, though i do python and other programs via Linux.

Can you advice the best IDE on Linux to use with mingw installed? Or which IDE did you use on Linux?

**Comment by quantumcore** [comment]
Well it's not ideal to Code WinApi C/C++ on Linux. But whenever I do it's for testing only. I only use Visual Studio Code for all types of development. And if you want to have an **IDE like feel and code WINAPI on Linux**, Just install mingw-w64 and add include paths to VS Code. And of course you can Run the Executables using Wine.

**Comment by quantumcore** [comment]
Closing this due to no response from OP.
