### ISSUE TITLE
 Error building Paradoxia Client.

### ISSUE THREAD

**Issue by phanthuthao** [quantumcored/paradoxiaRAT#7]
pls help me, I can not build"
paradoxia >> build                                                                                                                                                    
[+] Host : 192.168.0.103                                                                                                                                              
[+] Port : 443                                                                                                                                                        
[+] Installation Name (.exe) : ParadoxiaClient.exe                                                                                                                    
[+] Installation Folder name : ParadoxiaClient                                                                                                                        
[+] Output file name (.exe) : file.exe                                                                                                                           
[?] Would you like to build with Icon? (Y/n) : y                                                                                                                      
[+] Icon Path (.ico) : /home/joker2020/Downloads/images.ico                                                                                                           
[X] Error building Paradoxia Client.

**Comment by quantumcore** [comment]
This is caused by multiple defination error during build, I'm working on a fix for it. Thanks for reporting!

**Comment by etaylor77** [comment]
Following as I am suffering the same issue.

**Comment by quantumcore** [comment]
Reclone the latest or ``git pull``. I have pushed a potential fix for this bug. Trying to test it now.

**Comment by quantumcore** [comment]
I just tested and it seems to be working now. 
Requesting @phanthuthao to Confirm and close this. 
Thanks guys.

**Comment by etaylor77** [comment]
@quantumcore - Just a sec and I will test my setup

**Comment by etaylor77** [comment]
Thanks so much for getting this resolved! Hopefully the poster will confirm as well.

![image](https://user-images.githubusercontent.com/12686164/98996913-a4805180-2501-11eb-912d-bc4a2087bb19.png)

**Comment by phanthuthao** [comment]
Thanks so much

**Comment by phanthuthao** [comment]
Thanks so much.

Vào Th 5, 12 thg 11, 2020 vào lúc 15:11 WreckITRalph <
notifications@github.com> đã viết:
